version: '3.7'
services:
  search:
    restart: always
    container_name: search
    build: ./search
    ports:
      - "8080:8080"
    environment:
      - INDEX_NAME=${INDEX_NAME}
      - INJESTION_FILE=${INJESTION_FILE}
    depends_on:
      - es0
      - bertserving

  bertserving:
    build: ./bertserving
    container_name: bertserving
    ports:
      - "5555:5555"
      - "5556:5556"
    environment:
      - CUDA_VISIBLE_DEVICES = ${CUDA_VISIBLE_DEVICES}
      - MODEL_NAME = ${MODEL_NAME}
    volumes:
      - "./${MODEL_NAME}:/model"
    depends_on:
      - es0
  
  es0:
    restart: always
    container_name: es0
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
    tty: true
    ports:
      - 9200:9200

volumes:
  es-data:
    driver: local